"""
Django settings for registro project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env
load_dotenv(BASE_DIR / ".env")

# ---- .env support (safe) ----
OBD_INGEST_API_KEY = os.getenv("OBD_INGEST_API_KEY", "")
OBD_INGEST_MAX_SKEW_SECONDS = int(os.getenv("OBD_INGEST_MAX_SKEW_SECONDS", "300"))

# Rellenar nulls con demo sin contaminar producción
OBD_DEMO_FILL_MISSING = os.getenv("OBD_DEMO_FILL_MISSING", "0") == "1"

# añadir variables y fallbacks para WhatsApp
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN", "")
WHATSAPP_PHONE_ID = os.getenv("WHATSAPP_PHONE_ID", "")
WHATSAPP_DEBUG_TO = os.getenv("WHATSAPP_DEBUG_TO", "")  # usar en DEBUG

# variables para Twilio WhatsApp
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER", "")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = "django-insecure-9g*gvmoe=ny&7o98m3g6pzg5=##q$8hz_4z)3-8u&utxfmd4k$"

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = True

# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     ".onrender.com",  # para despliegue en render.com
# ]


def env_list(name, default=""):
    return [
        item.strip() for item in os.getenv(name, default).split(",") if item.strip()
    ]


DEBUG = os.getenv("DEBUG", "True") == "True"
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,1.0.0.127.in-addr.arpa,.onrender.com",
)
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "https://*.onrender.com,http://1.0.0.127.in-addr.arpa:8000",
)
if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# ALLOWED_HOSTS = os.getenv(
#     "ALLOWED_HOSTS", "localhost,127.0.0.1,1.0.0.127.in-addr.arpa,.onrender.com"
# ).split(",")

# CSRF para Render
# CSRF_TRUSTED_ORIGINS = [
#     "https://*.onrender.com",
# ]

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS", "https://*.onrender.com,http://1.0.0.127.in-addr.arpa:8000"
).split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
    # api rest framework
    "rest_framework",
    "corsheaders",
    # mi app
    "app1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # para servir estáticos en render.com
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

# CORS_ALLOWED_ORIGINS = [
#     # emuladores locales
#     "http://10.0.2.2:8080",
#     "http://localhost:8080",
# ]

CORS_ALLOWED_ORIGINS = [
    "http://10.0.2.2:8080",
    "http://localhost:8080",
    "http://1.0.0.127.in-addr.arpa:8000",  # opcional si us0 front en ese host
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated"),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny"),
}

ROOT_URLCONF = "registro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "registro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# configuracion para postgresql local
# DATABASES = {
#     # "default": {
#     #     "ENGINE": "django.db.backends.sqlite3",
#     #     "NAME": BASE_DIR / "db.sqlite3",
#     # }
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "odbiiprueba",
#         # "NAME": "obd_data",
#         "USER": "postgres",
#         "PASSWORD": "jprzc",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }


# bloque de base de datos
if DATABASE_URL:
    db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    if db_config["ENGINE"] == "django.db.backends.postgresql":
        db_config.setdefault("OPTIONS", {})
        db_config["OPTIONS"]["sslmode"] = "require"
    DATABASES = {"default": db_config}
elif DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "odbiiprueba",
            "USER": "postgres",
            "PASSWORD": "jprzc",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }
else:
    raise ImproperlyConfigured("DATABASE_URL no está configurado en producción.")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# configuracion de crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# configuracion de archivos multimedia
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# --------------------------------------------------------
# Boble de seguridad
# --------------------------------------------------------
# variables para render
# DEBUG = os.getenv("DEBUG", "True") == "True"
# SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# temporal
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = "SAMEORIGIN"
X_FRAME_OPTIONS = "DENY"
if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# enviar email
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "noreply@appmantenimiento.com"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "tu_correo@gmail.com"
EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER", ""
)  # quien envía (debe ser Gmail para este backend)
# EMAIL_HOST_PASSWORD = "tu_clave_de_aplicacion"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
