# Generated by Django 5.2.8 on 2026-01-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mantenimiento",
            name="vehiculo",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mantenimientos",
                to="app1.vehiculo",
            ),
            preserve_default=False,
        ),
    ]
