# Generated by Django 5.2.8 on 2026-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app1", "0003_mantenimiento_vehiculo")]

    operations = [
        migrations.CreateModel(
            name="obddata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_code", models.CharField(db_index=True, max_length=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("engine_rpm", models.FloatField(blank=True, null=True)),
                ("vehicle_speed_kph", models.FloatField(blank=True, null=True)),
                ("engine_temp_c", models.FloatField(blank=True, null=True)),
                ("coolant_temp_c", models.FloatField(blank=True, null=True)),
                ("oil_pressure_psi", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "obd_data",
                "ordering": ["-timestamp"],
            },
        ),
        # indices de optimización
        # migrations.AddIndex(
        #     model_name="obddata",
        #     index=models.Index(
        #         fields=["vehicle_code", "timestamp"], name="idx_vehicle_time"
        #     ),
        # ),
    ]
