# Generated by Django 5.2.8 on 2026-01-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_obddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='obddata',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obd_records', to='app1.vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_comsbustible',
            field=models.CharField(default='Gasolina', max_length=20),
        ),
        migrations.AlterField(
            model_name='obddata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='obddata',
            name='vehicle_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='obddata',
            index=models.Index(fields=['vehicle_code', 'timestamp'], name='idx_vehicle_time'),
        ),
    ]
