# Generated by Django 5.2.8 on 2026-01-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_obddata_vehiculo_vehiculo_tipo_comsbustible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('severidad', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='app1.vehiculo')),
            ],
        ),
    ]
