# Generated by Django 5.2.8 on 2026-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_recomendacionmantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='obddata',
            name='battery_voltage_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obddata',
            name='engine_failure_imminent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obddata',
            name='fuel_level_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obddata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='obddata',
            name='vehicle_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
