# Generated by Django 5.2.8 on 2026-02-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='obd_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
