# Generated by Django 5.2.8 on 2026-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_vehiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, default='vehiculos/imgdefault.png', null=True, upload_to='vehiculos/'),
        ),
    ]
