# Generated by Django 6.0.3 on 2026-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='nombre_mecanico',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='telefono_mecanico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
