# Generated by Django 6.0.3 on 2026-05-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_mantenimiento_nombre_mecanico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obddata',
            name='odometer_reading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
